"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",

    "drf_yasg",

    'zeroproject',
]




REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework.authentication.SessionAuthentication',
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE", default="django.db.backends.postgresql"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = "zeroproject.CustomUser"


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "AUTH_HEADER_TYPES": ("Bearer",),
}



JAZZMIN_SETTINGS = {
    "site_title": "Reklama Paneli",
    "site_header": "Metro Reklama Admin",
    "site_brand": "Metro Reklama",
    "welcome_sign": "Xush kelibsiz, admin!",
    "copyright": "© 2025 Metro",

    # 🔥 Dark Mode
    "theme": "darkly",

    # 🔥 Logotiplar (static/logo/ ichida bo‘ladi)
    "site_logo": "logo/admin_logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "logo/favicon.png",

    # 🔥 Iconlar (faqat siz aytgan modellardan)
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",

        # === Siz bergan modellarga ikonlar ===
        "zeroproject.MahsulotKategoriya": "fas fa-tags",
        "zeroproject.MahsulotBrend": "fas fa-tag",
        "zeroproject.Mahsulot": "fas fa-box",
        "zeroproject.Ombor": "fas fa-warehouse",
        "zeroproject.YetkazibBeruvchi": "fas fa-truck",
        "zeroproject.OmborKirim": "fas fa-arrow-down",
        "zeroproject.OmborChiqim": "fas fa-arrow-up",
        "zeroproject.MahsulotNarxi": "fas fa-money-bill-wave",
        "zeroproject.MahsulotSoni": "fas fa-sort-numeric-up",
        "zeroproject.OmborKochirish": "fas fa-exchange-alt",
        "zeroproject.Xarajat": "fas fa-receipt",
        "zeroproject.KassaKirim": "fas fa-cash-register",
        "zeroproject.Buyurtma": "fas fa-shopping-cart",
        "zeroproject.BuyurtmaMahsulot": "fas fa-cart-plus",
        "zeroproject.Tolov": "fas fa-credit-card",
        "zeroproject.Filial": "fas fa-building",
        "zeroproject.NarxSozlamalari": "fas fa-cog",
    },

    "show_sidebar": True,
    "navigation_expanded": True,

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    "changeform_format": "horizontal_tabs",
}



JAZZMIN_UI_TWEAKS = {
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-info",
    "theme": "cyborg",
}
