# Generated by Django 5.2.8 on 2025-12-01 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotKategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('filial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rasmiy_nomi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=255)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('valyuta_turi', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ismi', models.CharField(max_length=255)),
                ('mijoz_telefoni', models.CharField(max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('kassir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KassaKirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirim_turi', models.CharField(max_length=255)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('kassir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zeroproject.buyurtma')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeroproject.mahsulotbrend'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='kategoriya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeroproject.mahsulotkategoriya'),
        ),
        migrations.CreateModel(
            name='MahsulotNarxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chegirma', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='NarxSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_turi', models.CharField(max_length=255)),
                ('soni', models.IntegerField()),
                ('foiz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.filial')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotSoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='OmborChiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('tasdiqlash', models.BooleanField(default=False)),
                ('sana', models.DateField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='OmborKochirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('sana', models.DateField(auto_now_add=True)),
                ('hozirgi_ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ombor', to='zeroproject.ombor')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
                ('yangi_ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ombor', to='zeroproject.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_kodi', models.CharField(max_length=255)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(auto_now_add=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xarajat_turi', models.CharField(max_length=255)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('kassir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OmborKirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('valyuta_turi', models.CharField(max_length=10)),
                ('kurs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tolov_turi', models.CharField(max_length=20)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.mahsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroproject.ombor')),
                ('yetkazib_beruvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeroproject.yetkazibberuvchi')),
            ],
        ),
    ]
